version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/lms-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - lms-network

  api:
    build: ./backend/lms_project
    ports:
      - "8000:8000"
    volumes:
      - ./backend/lms_project:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lms_db
      - POSTGRES_PORT=5432
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
    networks:
      - lms-network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lms_db
    ports:
      - "5432:5432"
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  postgres_data:
